apiVersion: apps/v1
kind: Deployment
metadata:
  name: vin-decoder-deployment
spec:
  replicas: 2
  # Seleziona i Pods da replicare
  selector:
    matchLabels:
      app: vin-decoder
  template:
    metadata:
      labels:
        app: vin-decoder
    spec:
      containers:
      - name: vin-decoder
        image: pax7898/vin_decoder
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: vin-decoder-service
spec:
  # type: ClusterIP #Internal Service
  type: LoadBalancer #External Service
  selector:
    app: vin-decoder
  ports:
    - protocol: TCP
      port: 8081   # external Port (within the cluster)
      targetPort: 8081 # internal Port (within the Pod)